# Generated by Django 6.1.1 on 2026-09-30 19:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Imponibile')),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Totale IVA')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Totale documento')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numero')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Consegna prevista')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('sent', 'Inviato'), ('confirmed', 'Confermato'), ('received_partial', 'Parzialmente ricevuto'), ('received', 'Ricevuto'), ('cancelled', 'Annullato')], default='draft', max_length=20, verbose_name='Stato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentterm', verbose_name='Condizione di pagamento')),
                ('source_sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='sales.salesorder', verbose_name='Da ordine cliente')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='contacts.contact', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Ordine fornitore',
                'verbose_name_plural': 'Ordini fornitore',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posizione')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descrizione')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Quantità')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Prezzo unitario')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Sconto %')),
                ('qty_received', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Quantità ricevuta')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder', verbose_name='Ordine fornitore')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='Articolo')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure', verbose_name='U.d.M.')),
                ('vat_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.vatrate', verbose_name='IVA')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('name', models.CharField(max_length=120, verbose_name='Nome listino')),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Valido dal')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valido fino al')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_lists', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='contacts.contact', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Listino fornitore',
                'verbose_name_plural': 'Listini fornitori',
                'ordering': ['supplier__name', '-valid_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceListAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Variazione %')),
                ('items_count', models.PositiveIntegerField(default=0, verbose_name='Articoli aggiornati')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applicata il')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Applicata da')),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='purchasing.supplierpricelist', verbose_name='Listino')),
            ],
            options={
                'verbose_name': 'Variazione listino',
                'verbose_name_plural': 'Variazioni listino',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Prezzo')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Sconto %')),
                ('min_qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Quantità minima')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='catalog.product', verbose_name='Articolo')),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.supplierpricelist', verbose_name='Listino')),
            ],
            options={
                'verbose_name': 'Voce di listino',
                'verbose_name_plural': 'Voci di listino',
                'ordering': ['product__name'],
                'constraints': [models.UniqueConstraint(fields=('pricelist', 'product'), name='unique_product_per_pricelist')],
            },
        ),
    ]
