# Generated by Django 6.1.1 on 2026-10-01 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_contact_active_name_idx_and_more'),
        ('core', '0003_companysettings_document_color_companysettings_logo'),
        ('purchasing', '0001_initial'),
        ('sales', '0002_salesorderline_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', '-date'], name='po_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', '-date'], name='po_supplier_date_idx'),
        ),
    ]
