# Generated by Django 6.1.1 on 2026-10-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchaseorder_job_purchaseorderline_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='supplier_code',
            field=models.CharField(blank=True, db_index=True, help_text="Codice con cui il fornitore identifica l'articolo nel suo listino.", max_length=60, verbose_name='Codice fornitore'),
        ),
    ]
