# Generated by Django 6.1.1 on 2026-09-30 19:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Imponibile')),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Totale IVA')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Totale documento')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numero')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valido fino al')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Vostro riferimento')),
                ('notes', models.TextField(blank=True, verbose_name='Note interne')),
                ('terms_text', models.TextField(blank=True, verbose_name='Condizioni (stampate)')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('sent', 'Inviato'), ('accepted', 'Accettato'), ('rejected', 'Rifiutato'), ('converted', 'Convertito in ordine')], default='draft', max_length=20, verbose_name='Stato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='contacts.contact', verbose_name='Cliente')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentterm', verbose_name='Condizione di pagamento')),
            ],
            options={
                'verbose_name': 'Preventivo',
                'verbose_name_plural': 'Preventivi',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posizione')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descrizione')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Quantità')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Prezzo unitario')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Sconto %')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='Articolo')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quote', verbose_name='Preventivo')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure', verbose_name='U.d.M.')),
                ('vat_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.vatrate', verbose_name='IVA')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Imponibile')),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Totale IVA')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Totale documento')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numero')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Consegna prevista')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Vostro riferimento')),
                ('notes', models.TextField(blank=True, verbose_name='Note interne')),
                ('terms_text', models.TextField(blank=True, verbose_name='Condizioni (stampate)')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('confirmed', 'Confermato'), ('delivered', 'Consegnato'), ('cancelled', 'Annullato')], default='draft', max_length=20, verbose_name='Stato')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confermato il')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Consegnato il')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='contacts.contact', verbose_name='Cliente')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentterm', verbose_name='Condizione di pagamento')),
                ('source_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_orders', to='sales.quote', verbose_name='Da preventivo')),
            ],
            options={
                'verbose_name': 'Ordine cliente',
                'verbose_name_plural': 'Ordini cliente',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posizione')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descrizione')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Quantità')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Prezzo unitario')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Sconto %')),
                ('qty_delivered', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Quantità consegnata')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder', verbose_name='Ordine')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='Articolo')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure', verbose_name='U.d.M.')),
                ('vat_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.vatrate', verbose_name='IVA')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
    ]
