# Generated by Django 6.1.1 on 2026-09-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Costo di acquisto al momento della conferma, usato per la marginalità.', max_digits=12, null=True, verbose_name='Costo unitario'),
        ),
    ]
