# Generated by Django 6.1.1 on 2026-10-01 04:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_product_active_name_idx_and_more'),
        ('contacts', '0002_contact_contact_active_name_idx_and_more'),
        ('core', '0003_companysettings_document_color_companysettings_logo'),
        ('sales', '0002_salesorderline_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome modello')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrizione')),
                ('terms_text', models.TextField(blank=True, verbose_name='Condizioni (stampate)')),
                ('notes', models.TextField(blank=True, verbose_name='Note interne')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordine di visualizzazione')),
            ],
            options={
                'verbose_name': 'Modello di preventivo',
                'verbose_name_plural': 'Modelli di preventivo',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posizione')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descrizione')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Quantità')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Prezzo unitario')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Sconto %')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', '-date'], name='quote_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['customer', '-date'], name='quote_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', '-date'], name='order_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer', '-date'], name='order_customer_date_idx'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creato da'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentterm', verbose_name='Condizione di pagamento'),
        ),
        migrations.AddField(
            model_name='quotetemplateline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='Articolo'),
        ),
        migrations.AddField(
            model_name='quotetemplateline',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quotetemplate', verbose_name='Modello'),
        ),
        migrations.AddField(
            model_name='quotetemplateline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure', verbose_name='U.d.M.'),
        ),
        migrations.AddField(
            model_name='quotetemplateline',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.vatrate', verbose_name='IVA'),
        ),
    ]
