# Generated by Django 6.1.1 on 2026-10-01 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('sales', '0003_quotetemplate_quotetemplateline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='jobs.job', verbose_name='Cantiere'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='section',
            field=models.CharField(blank=True, help_text='Es. ambiente o fase (Bagno 1, Scavo, Finiture…). Righe consecutive con la stessa sezione vengono raggruppate.', max_length=80, verbose_name='Sezione'),
        ),
        migrations.AddField(
            model_name='quotetemplateline',
            name='section',
            field=models.CharField(blank=True, help_text='Es. ambiente o fase (Bagno 1, Scavo, Finiture…). Righe consecutive con la stessa sezione vengono raggruppate.', max_length=80, verbose_name='Sezione'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='jobs.job', verbose_name='Cantiere'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='section',
            field=models.CharField(blank=True, help_text='Es. ambiente o fase (Bagno 1, Scavo, Finiture…). Righe consecutive con la stessa sezione vengono raggruppate.', max_length=80, verbose_name='Sezione'),
        ),
    ]
