# Generated by Django 6.1.1 on 2026-10-01 15:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_sale_discount_pct'),
        ('sales', '0004_quote_job_quoteline_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='commission_contact',
            field=models.ForeignKey(blank=True, help_text='Chi ha presentato il cliente e percepisce la provvigione.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_commissions', to='contacts.contact', verbose_name='Provvigione a'),
        ),
        migrations.AddField(
            model_name='quote',
            name='commission_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Percentuale sull'imponibile. Lascia a 0 se non c'è provvigione.", max_digits=5, verbose_name='Provvigione %'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='commission_contact',
            field=models.ForeignKey(blank=True, help_text='Chi ha presentato il cliente e percepisce la provvigione.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_commissions', to='contacts.contact', verbose_name='Provvigione a'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='commission_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Percentuale sull'imponibile. Lascia a 0 se non c'è provvigione.", max_digits=5, verbose_name='Provvigione %'),
        ),
    ]
