# Generated by Django 6.1.1 on 2026-10-03 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_sale_discount_pct'),
        ('core', '0012_inboundemail_is_internal_inboundemail_is_relevant_and_more'),
        ('jobs', '0002_remove_asset_asset_serial_idx_and_more'),
        ('sales', '0005_quote_commission_contact_quote_commission_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', 'delivered_at'], name='order_delivered_idx'),
        ),
    ]
