# Generated by Django 6.1.1 on 2026-10-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesorder_order_delivered_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='line_type',
            field=models.CharField(choices=[('article', 'Articolo'), ('section', 'Sezione'), ('subsection', 'Sottosezione'), ('note', 'Nota')], default='article', help_text='Sezione, sottosezione e nota sono righe di testo: non hanno prezzo e non entrano nei totali.', max_length=12, verbose_name='Tipo riga'),
        ),
        migrations.AddField(
            model_name='quotetemplateline',
            name='line_type',
            field=models.CharField(choices=[('article', 'Articolo'), ('section', 'Sezione'), ('subsection', 'Sottosezione'), ('note', 'Nota')], default='article', help_text='Sezione, sottosezione e nota sono righe di testo: non hanno prezzo e non entrano nei totali.', max_length=12, verbose_name='Tipo riga'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='line_type',
            field=models.CharField(choices=[('article', 'Articolo'), ('section', 'Sezione'), ('subsection', 'Sottosezione'), ('note', 'Nota')], default='article', help_text='Sezione, sottosezione e nota sono righe di testo: non hanno prezzo e non entrano nei totali.', max_length=12, verbose_name='Tipo riga'),
        ),
    ]
