# Generated by Django 6.1.1 on 2026-10-01 05:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_is_kit_product_parent_and_more'),
        ('contacts', '0003_contact_sale_discount_pct'),
        ('core', '0006_alter_numbersequence_doc_type'),
        ('jobs', '0001_initial'),
        ('purchasing', '0003_purchaseorder_job_purchaseorderline_section'),
        ('sales', '0004_quote_job_quoteline_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numero')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('issued', 'Emesso'), ('cancelled', 'Annullato')], default='draft', max_length=20, verbose_name='Stato')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Emesso il')),
                ('invoiced', models.BooleanField(default=False, verbose_name='Fatturato')),
                ('transport_reason', models.CharField(blank=True, default='Vendita', max_length=100, verbose_name='Causale trasporto')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Vettore')),
                ('packages', models.PositiveIntegerField(blank=True, null=True, verbose_name='N. colli')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso (kg)')),
                ('destination', models.TextField(blank=True, help_text="Se vuoto usa l'indirizzo del cantiere o del cliente.", verbose_name='Destinazione')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='contacts.contact', verbose_name='Cliente')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='jobs.job', verbose_name='Cantiere')),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='sales.salesorder', verbose_name='Da ordine cliente')),
            ],
            options={
                'verbose_name': 'DDT',
                'verbose_name_plural': 'DDT',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posizione')),
                ('section', models.CharField(blank=True, help_text='Es. ambiente o fase (Bagno 1, Scavo, Finiture…). Righe consecutive con la stessa sezione vengono raggruppate.', max_length=80, verbose_name='Sezione')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descrizione')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Quantità')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Prezzo unitario')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Sconto %')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.deliverynote', verbose_name='DDT')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='Articolo')),
                ('source_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_note_lines', to='sales.salesorderline', verbose_name='Riga ordine collegata')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure', verbose_name='U.d.M.')),
                ('vat_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.vatrate', verbose_name='IVA')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Imponibile')),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Totale IVA')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Totale documento')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numero interno')),
                ('supplier_reference', models.CharField(blank=True, max_length=50, verbose_name='Numero documento fornitore')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Scadenza pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('registered', 'Da pagare'), ('paid', 'Pagata'), ('cancelled', 'Annullata')], default='draft', max_length=20, verbose_name='Stato')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Registrata il')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagata il')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='jobs.job', verbose_name='Cantiere')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentterm', verbose_name='Condizione di pagamento')),
                ('source_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='purchasing.purchaseorder', verbose_name='Da ordine fornitore')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='contacts.contact', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Fattura ricevuta',
                'verbose_name_plural': 'Fatture ricevute',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posizione')),
                ('section', models.CharField(blank=True, help_text='Es. ambiente o fase (Bagno 1, Scavo, Finiture…). Righe consecutive con la stessa sezione vengono raggruppate.', max_length=80, verbose_name='Sezione')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descrizione')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Quantità')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Prezzo unitario')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Sconto %')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.purchaseinvoice', verbose_name='Fattura')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='Articolo')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure', verbose_name='U.d.M.')),
                ('vat_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.vatrate', verbose_name='IVA')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Imponibile')),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Totale IVA')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Totale documento')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numero')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Scadenza pagamento')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Vostro riferimento')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('issued', 'Emessa'), ('sent', 'Inviata'), ('paid', 'Pagata'), ('cancelled', 'Annullata')], default='draft', max_length=20, verbose_name='Stato')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Emessa il')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Inviata il')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagata il')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='contacts.contact', verbose_name='Cliente')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='jobs.job', verbose_name='Cantiere')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentterm', verbose_name='Condizione di pagamento')),
                ('source_delivery_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='billing.deliverynote', verbose_name='Da DDT')),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='sales.salesorder', verbose_name='Da ordine cliente')),
            ],
            options={
                'verbose_name': 'Fattura emessa',
                'verbose_name_plural': 'Fatture emesse',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posizione')),
                ('section', models.CharField(blank=True, help_text='Es. ambiente o fase (Bagno 1, Scavo, Finiture…). Righe consecutive con la stessa sezione vengono raggruppate.', max_length=80, verbose_name='Sezione')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descrizione')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Quantità')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Prezzo unitario')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Sconto %')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.salesinvoice', verbose_name='Fattura')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='Articolo')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure', verbose_name='U.d.M.')),
                ('vat_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.vatrate', verbose_name='IVA')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScannedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('file', models.FileField(upload_to='scans/%Y/%m/', verbose_name='File')),
                ('original_name', models.CharField(blank=True, max_length=200, verbose_name='Nome file')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Testo estratto (OCR)')),
                ('doc_number', models.CharField(blank=True, max_length=50, verbose_name='Numero documento')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='Data documento')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Totale letto')),
                ('status', models.CharField(choices=[('new', 'Da elaborare'), ('ok', 'Elaborato'), ('error', 'Errore')], default='new', max_length=20, verbose_name='Stato')),
                ('error_message', models.CharField(blank=True, max_length=300, verbose_name='Errore')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='billing.purchaseinvoice', verbose_name='Fattura collegata')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_documents', to='contacts.contact', verbose_name='Fornitore riconosciuto')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Caricato da')),
            ],
            options={
                'verbose_name': 'Documento acquisito',
                'verbose_name_plural': 'Documenti acquisiti',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['status', '-date'], name='ddt_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['customer', '-date'], name='ddt_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['status', '-date'], name='pinv_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['supplier', '-date'], name='pinv_supplier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['status', '-date'], name='sinv_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['customer', '-date'], name='sinv_customer_date_idx'),
        ),
    ]
