# Generated by Django 6.1.1 on 2026-10-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='sdi_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='Esito / nota SDI'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sdi_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inviata allo SDI il'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sdi_status',
            field=models.CharField(choices=[('not_sent', 'Non inviata'), ('generated', 'XML generato'), ('sent', 'Inviata allo SDI'), ('delivered', 'Consegnata'), ('accepted', 'Accettata'), ('rejected', 'Scartata'), ('failed', 'Mancata consegna')], default='not_sent', max_length=20, verbose_name='Stato SDI'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='xml_file',
            field=models.FileField(blank=True, upload_to='sdi/%Y/', verbose_name='File XML (FatturaPA)'),
        ),
    ]
