# Generated by Django 6.1.1 on 2026-10-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_salesinvoice_sdi_note_salesinvoice_sdi_sent_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScannedDocument',
        ),
    ]
