# Generated by Django 6.1.1 on 2026-10-03 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_delete_scanneddocument'),
        ('contacts', '0003_contact_sale_discount_pct'),
        ('core', '0012_inboundemail_is_internal_inboundemail_is_relevant_and_more'),
        ('jobs', '0002_remove_asset_asset_serial_idx_and_more'),
        ('purchasing', '0003_purchaseorder_job_purchaseorderline_section'),
        ('sales', '0005_quote_commission_contact_quote_commission_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['status', 'due_date'], name='pinv_due_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['status', 'due_date'], name='sinv_due_idx'),
        ),
    ]
