# Generated by Django 6.1.1 on 2026-10-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_purchaseinvoice_pinv_due_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Valore del cantiere al momento dell'emissione (per SAL, acconti e saldi).", max_digits=12, null=True, verbose_name='Valore contratto'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='kind',
            field=models.CharField(choices=[('invoice', 'Fattura'), ('advance', 'Acconto'), ('sal', 'SAL (avanzamento lavori)'), ('balance', 'Saldo')], default='invoice', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sal_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero SAL'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sal_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Avanzamento %'),
        ),
    ]
