# Generated by Django 6.1.1 on 2026-10-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_salesinvoice_contract_amount_salesinvoice_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynoteline',
            name='line_type',
            field=models.CharField(choices=[('article', 'Articolo'), ('section', 'Sezione'), ('subsection', 'Sottosezione'), ('note', 'Nota')], default='article', help_text='Sezione, sottosezione e nota sono righe di testo: non hanno prezzo e non entrano nei totali.', max_length=12, verbose_name='Tipo riga'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='line_type',
            field=models.CharField(choices=[('article', 'Articolo'), ('section', 'Sezione'), ('subsection', 'Sottosezione'), ('note', 'Nota')], default='article', help_text='Sezione, sottosezione e nota sono righe di testo: non hanno prezzo e non entrano nei totali.', max_length=12, verbose_name='Tipo riga'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='line_type',
            field=models.CharField(choices=[('article', 'Articolo'), ('section', 'Sezione'), ('subsection', 'Sottosezione'), ('note', 'Nota')], default='article', help_text='Sezione, sottosezione e nota sono righe di testo: non hanno prezzo e non entrano nei totali.', max_length=12, verbose_name='Tipo riga'),
        ),
    ]
