# Generated by Django 6.1.2 on 2026-10-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_deliverynoteline_line_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='is_advance_deduction',
            field=models.BooleanField(default=False, help_text='Riga negativa che scala un acconto fisso già fatturato per lo stesso ordine.', verbose_name='Storno acconto'),
        ),
    ]
