# Generated by Django 6.1.1 on 2026-09-30 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Codice')),
                ('name', models.CharField(max_length=200, verbose_name='Ragione sociale / Nome')),
                ('is_customer', models.BooleanField(default=True, verbose_name='Cliente')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Fornitore')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='Partita IVA')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Codice fiscale')),
                ('sdi_code', models.CharField(blank=True, max_length=10, verbose_name='Codice destinatario SDI')),
                ('pec', models.EmailField(blank=True, max_length=254, verbose_name='PEC')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('mobile', models.CharField(blank=True, max_length=40, verbose_name='Cellulare')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='Sito web')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Indirizzo')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('province', models.CharField(blank=True, max_length=5, verbose_name='Provincia')),
                ('country', models.CharField(blank=True, default='Italia', max_length=100, verbose_name='Paese')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentterm', verbose_name='Condizione di pagamento')),
                ('tags', models.ManyToManyField(blank=True, related_name='contacts', to='core.tag', verbose_name='Etichette')),
            ],
            options={
                'verbose_name': 'Contatto',
                'verbose_name_plural': 'Contatti',
                'ordering': ['name'],
            },
        ),
    ]
