# Generated by Django 6.1.1 on 2026-10-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0003_companysettings_document_color_companysettings_logo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['active', 'name'], name='contact_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['vat_number'], name='contact_vat_idx'),
        ),
    ]
