# Generated by Django 6.1.1 on 2026-10-01 05:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_contact_active_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sale_discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Proposto automaticamente nelle righe dei preventivi e degli ordini.', max_digits=5, verbose_name='Sconto vendite abituale %'),
        ),
    ]
