# Generated by Django 6.1.1 on 2026-10-06 17:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_sale_discount_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='purchase_discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Applicato ai prezzi di acquisto degli articoli del fornitore che non hanno un listino dedicato.', max_digits=5, verbose_name='Sconto acquisto base %'),
        ),
    ]
