# Generated by Django 6.1.1 on 2026-10-01 05:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_is_kit_product_parent_and_more'),
        ('contacts', '0003_contact_sale_discount_pct'),
        ('sales', '0003_quotetemplate_quotetemplateline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Codice')),
                ('name', models.CharField(max_length=150, verbose_name='Nome cantiere')),
                ('status', models.CharField(choices=[('survey', 'Sopralluogo'), ('quote', 'In preventivazione'), ('confirmed', 'Confermato'), ('in_progress', 'In esecuzione'), ('testing', 'Collaudo'), ('closed', 'Chiuso'), ('cancelled', 'Annullato')], default='survey', max_length=20, verbose_name='Stato')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Indirizzo')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('province', models.CharField(blank=True, max_length=5, verbose_name='Provincia')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Inizio lavori')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fine prevista')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='contacts.contact', verbose_name='Cliente')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile')),
            ],
            options={
                'verbose_name': 'Cantiere',
                'verbose_name_plural': 'Cantieri',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('serial_number', models.CharField(max_length=80, verbose_name='Numero di serie')),
                ('installed_on', models.DateField(blank=True, null=True, verbose_name='Data installazione')),
                ('warranty_months', models.PositiveSmallIntegerField(default=24, verbose_name='Garanzia (mesi)')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Note')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='contacts.contact', verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='catalog.product', verbose_name='Articolo')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='jobs.job', verbose_name='Cantiere')),
            ],
            options={
                'verbose_name': 'Seriale installato',
                'verbose_name_plural': 'Seriali installati',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('name', models.CharField(max_length=150, verbose_name='Descrizione')),
                ('frequency', models.CharField(choices=[('monthly', 'Mensile'), ('bimonthly', 'Bimestrale'), ('quarterly', 'Trimestrale'), ('semiannual', 'Semestrale'), ('annual', 'Annuale'), ('custom', 'Personalizzata')], default='annual', max_length=20, verbose_name='Frequenza')),
                ('next_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Prossima esecuzione')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plans', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='contacts.contact', verbose_name='Cliente')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plans', to='jobs.job', verbose_name='Cantiere')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plans', to='sales.quotetemplate', verbose_name='Modello di preventivo')),
            ],
            options={
                'verbose_name': 'Manutenzione programmata',
                'verbose_name_plural': 'Manutenzioni programmate',
                'ordering': ['next_date', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='job_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['customer', 'name'], name='job_customer_name_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='asset_serial_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('product', 'serial_number'), name='unique_serial_per_product'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['active', 'next_date'], name='plan_active_next_idx'),
        ),
    ]
