# Generated by Django 6.1.1 on 2026-10-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asset',
            name='asset_serial_idx',
        ),
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_serial_per_product',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
