# Generated by Django 6.1.1 on 2026-09-30 19:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='La mia azienda', max_length=200, verbose_name='Ragione sociale')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='Partita IVA')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Codice fiscale')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Indirizzo')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('province', models.CharField(blank=True, max_length=5, verbose_name='Provincia')),
                ('country', models.CharField(default='Italia', max_length=100, verbose_name='Paese')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='Sito web')),
                ('iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('quote_footer', models.TextField(blank=True, default='Pagamento: come concordato.\nPrezzi IVA esclusa salvo diversa indicazione.', verbose_name='Condizioni generali (in fondo ai documenti)')),
            ],
            options={
                'verbose_name': 'Dati azienda',
                'verbose_name_plural': 'Dati azienda',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('days', models.PositiveIntegerField(default=30, verbose_name='Giorni')),
                ('end_of_month', models.BooleanField(default=False, verbose_name='Fine mese')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Condizione di pagamento',
                'verbose_name_plural': 'Condizioni di pagamento',
                'ordering': ['days', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nome')),
                ('color', models.CharField(choices=[('primary', 'Blu'), ('success', 'Verde'), ('danger', 'Rosso'), ('warning', 'Giallo'), ('info', 'Azzurro'), ('secondary', 'Grigio'), ('dark', 'Scuro')], default='secondary', max_length=20, verbose_name='Colore')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Etichetta',
                'verbose_name_plural': 'Etichette',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Es. PZ, KG, MT', max_length=10, unique=True, verbose_name='Codice')),
                ('name', models.CharField(max_length=60, verbose_name='Descrizione')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Unità di misura',
                'verbose_name_plural': 'Unità di misura',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Es. 22, 10, N2.2', max_length=10, unique=True, verbose_name='Codice')),
                ('name', models.CharField(max_length=120, verbose_name='Descrizione')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5, verbose_name='Aliquota %')),
                ('nature', models.CharField(blank=True, help_text='Codice natura SDI, es. N2.2. Lasciare vuoto per le aliquote ordinarie.', max_length=10, verbose_name='Natura (fatturazione elettronica)')),
                ('is_default_sales', models.BooleanField(default=False, verbose_name='Predefinita per vendite')),
                ('is_default_purchase', models.BooleanField(default=False, verbose_name='Predefinita per acquisti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Aliquota IVA',
                'verbose_name_plural': 'Aliquote IVA',
                'ordering': ['-rate', 'code'],
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('quote', 'Preventivo'), ('sales_order', 'Ordine cliente'), ('purchase_order', 'Ordine fornitore')], max_length=30, verbose_name='Tipo documento')),
                ('year', models.PositiveSmallIntegerField(default=0, help_text='0 = numerazione continua senza anno', verbose_name='Anno')),
                ('prefix', models.CharField(max_length=20, verbose_name='Prefisso')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prossimo numero')),
                ('padding', models.PositiveSmallIntegerField(default=4, verbose_name='Zeri iniziali')),
            ],
            options={
                'verbose_name': 'Numerazione',
                'verbose_name_plural': 'Numerazioni',
                'ordering': ['doc_type', 'year'],
                'constraints': [models.UniqueConstraint(fields=('doc_type', 'year'), name='unique_sequence_per_type_year')],
            },
        ),
    ]
