# Generated by Django 6.1.1 on 2026-09-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='document_color',
            field=models.CharField(default='#1d4ed8', help_text='Colore principale di grafica e intestazioni nei documenti stampati.', max_length=7, verbose_name='Colore documenti'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Usato in alto nei documenti stampati (PNG o JPG).', null=True, upload_to='company/', verbose_name='Logo aziendale'),
        ),
    ]
