# Generated by Django 6.1.1 on 2026-10-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companysettings_document_color_companysettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='File')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Allegato',
                'verbose_name_plural': 'Allegati',
                'ordering': ['-created_at'],
            },
        ),
    ]
