# Generated by Django 6.1.1 on 2026-10-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attachment_job_attachment_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbersequence',
            name='doc_type',
            field=models.CharField(choices=[('quote', 'Preventivo'), ('sales_order', 'Ordine cliente'), ('purchase_order', 'Ordine fornitore'), ('delivery_note', 'DDT'), ('sales_invoice', 'Fattura emessa'), ('purchase_invoice', 'Fattura ricevuta')], max_length=30, verbose_name='Tipo documento'),
        ),
    ]
