# Generated by Django 6.1.1 on 2026-10-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_numbersequence_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='fiscal_regime',
            field=models.CharField(choices=[('RF01', 'RF01 – Ordinario'), ('RF02', 'RF02 – Contribuenti minimi'), ('RF04', 'RF04 – Agricoltura e pesca'), ('RF05', 'RF05 – Vendita sali e tabacchi'), ('RF15', 'RF15 – Agenzie viaggi'), ('RF16', 'RF16 – Agenti e rappresentanti'), ('RF17', 'RF17 – Vendita porta a porta'), ('RF18', 'RF18 – Altri casi'), ('RF19', 'RF19 – Regime forfettario')], default='RF01', help_text='Serve per la fatturazione elettronica (campo RegimeFiscale).', max_length=10, verbose_name='Regime fiscale'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='pec',
            field=models.EmailField(blank=True, help_text="Usata anche per l'invio delle fatture elettroniche allo SDI.", max_length=254, verbose_name='PEC'),
        ),
    ]
