# Generated by Django 6.1.1 on 2026-10-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companysettings_fiscal_regime_companysettings_pec'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='app_logo',
            field=models.ImageField(blank=True, help_text="Sostituisce l'icona in alto a sinistra nel gestionale (PNG con sfondo trasparente).", null=True, upload_to='company/', verbose_name='Logo del gestionale'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='document_style',
            field=models.CharField(choices=[('classico', 'Classico'), ('moderno', 'Moderno'), ('sobrio', 'Sobrio'), ('elegante', 'Elegante')], default='classico', max_length=10, verbose_name='Stile dei preventivi e documenti'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='theme_background',
            field=models.CharField(choices=[('soft', 'Azzurro tenue'), ('white', 'Bianco'), ('grey', 'Grigio chiaro'), ('warm', 'Caldo'), ('blue', 'Azzurro')], default='soft', max_length=10, verbose_name='Sfondo del gestionale'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='theme_color',
            field=models.CharField(default='#2563eb', help_text='Colore di menu, pulsanti e collegamenti.', max_length=7, verbose_name='Colore del gestionale'),
        ),
    ]
