# Generated by Django 6.1.1 on 2026-10-02 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_code'),
        ('core', '0008_companysettings_app_logo_and_more'),
        ('hr', '0002_collaborator_collaboratortimeentry_and_more'),
        ('jobs', '0002_remove_asset_asset_serial_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attachment',
            name='attachment_has_target',
        ),
        migrations.AddField(
            model_name='attachment',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hr.collaborator', verbose_name='Collaboratore'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('document', 'Documento'), ('site', 'Foto cantiere'), ('receipt', 'Bolla / acquisto')], default='document', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['kind', '-created_at'], name='attachment_kind_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), ('job__isnull', False), ('collaborator__isnull', False), _connector='OR'), name='attachment_has_target'),
        ),
    ]
