# Generated by Django 6.1.1 on 2026-10-02 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_attachment_attachment_has_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creato', 'Creato'), ('modificato', 'Modificato'), ('cancellato', 'Cancellato')], max_length=20, verbose_name='Azione')),
                ('model_name', models.CharField(max_length=60, verbose_name='Tipo')),
                ('object_id', models.CharField(blank=True, max_length=40, verbose_name='Identificativo')),
                ('object_label', models.CharField(blank=True, max_length=120, verbose_name='Oggetto')),
                ('details', models.CharField(blank=True, max_length=300, verbose_name='Dettagli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Attività',
                'verbose_name_plural': 'Registro attività',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_date_idx')],
            },
        ),
    ]
