# Generated by Django 6.1.1 on 2026-10-03 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_sale_discount_pct'),
        ('core', '0010_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('uid', models.CharField(max_length=64, unique=True, verbose_name='UID IMAP')),
                ('folder', models.CharField(default='INBOX', max_length=60, verbose_name='Cartella')),
                ('message_id', models.CharField(blank=True, max_length=255, verbose_name='Message-ID')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='Mittente')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='Email mittente')),
                ('recipients', models.CharField(blank=True, max_length=500, verbose_name='Destinatari')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Oggetto')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Ricevuta il')),
                ('body_text', models.TextField(blank=True, verbose_name='Testo')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML')),
                ('body_loaded', models.BooleanField(default=False, verbose_name='Corpo scaricato')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Allegati')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Letta il')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='contacts.contact', verbose_name='Contatto collegato')),
            ],
            options={
                'verbose_name': 'Email ricevuta',
                'verbose_name_plural': 'Posta ricevuta',
                'ordering': ['-received_at', '-pk'],
                'indexes': [models.Index(fields=['-received_at'], name='email_received_idx'), models.Index(fields=['read_at'], name='email_read_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('body', models.TextField(verbose_name='Messaggio')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Letto il')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_internal_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_internal_messages', to=settings.AUTH_USER_MODEL, verbose_name='Mittente')),
            ],
            options={
                'verbose_name': 'Messaggio interno',
                'verbose_name_plural': 'Messaggi interni',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='message_recipient_read_idx'), models.Index(fields=['sender', 'recipient'], name='message_pair_idx')],
            },
        ),
    ]
