# Generated by Django 6.1.1 on 2026-10-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_inboundemail_internalmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Da dominio aziendale'),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='is_relevant',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Rilevante'),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='È una risposta'),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='relevance',
            field=models.CharField(blank=True, max_length=30, verbose_name='Perché è rilevante'),
        ),
    ]
