# Generated by Django 6.1.1 on 2026-10-03 12:17

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_inboundemail_is_internal_inboundemail_is_relevant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/', validators=[apps.core.validators.valida_file_caricato], verbose_name='File'),
        ),
    ]
