# Generated by Django 6.1.1 on 2026-10-05 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_attachment_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='Indirizzo')),
                ('title', models.CharField(max_length=160, verbose_name='Titolo')),
                ('area', models.CharField(default='Generale', max_length=60, verbose_name='Sezione')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='Sommario')),
                ('body', models.TextField(help_text='Testo della guida (titoli, elenchi, link).', verbose_name='Contenuto')),
                ('roles', models.CharField(blank=True, help_text='Vuoto = tutti. Altrimenti i nomi dei ruoli separati da virgola (es. Vendite, Amministratore).', max_length=250, verbose_name='Ruoli che possono leggerla')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Ordine')),
                ('is_published', models.BooleanField(default=True, verbose_name='Pubblicata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages', to=settings.AUTH_USER_MODEL, verbose_name='Modificata da')),
            ],
            options={
                'verbose_name': 'Pagina della guida',
                'verbose_name_plural': 'Guida',
                'ordering': ['area', 'order', 'title'],
                'indexes': [models.Index(fields=['is_published', 'area', 'order'], name='wiki_visibile_idx')],
            },
        ),
    ]
