# Generated by Django 6.1.1 on 2026-10-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_wikipage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quote', 'Invio preventivo'), ('invoice', 'Invio fattura'), ('quote_reminder', 'Sollecito preventivo'), ('invoice_reminder', 'Sollecito fattura')], max_length=20, unique=True, verbose_name='Tipo')),
                ('subject', models.CharField(max_length=200, verbose_name='Oggetto')),
                ('body', models.TextField(verbose_name='Testo')),
            ],
            options={
                'verbose_name': 'Modello email',
                'verbose_name_plural': 'Modelli email',
                'ordering': ['kind'],
            },
        ),
    ]
