# Generated by Django 6.1.2 on 2026-10-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='sales_terms',
            field=models.TextField(blank=True, help_text='Lascia vuoto per usare il testo standard. Ammessi segnaposto {azienda} {indirizzo} {piva} {email} {telefono} e formattazione semplice (grassetto, elenchi).', verbose_name='Condizioni di vendita (preventivi, ordini e pagina pubblica)'),
        ),
    ]
