# Generated by Django 6.1.2 on 2026-10-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_indici_registro_attivita'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInCoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Destinatario')),
                ('subject', models.CharField(max_length=300, verbose_name='Oggetto')),
                ('body', models.TextField(verbose_name='Testo')),
                ('attachment', models.BinaryField(blank=True, null=True, verbose_name='Allegato')),
                ('attachment_name', models.CharField(blank=True, max_length=150, verbose_name='Nome allegato')),
                ('attachment_type', models.CharField(default='application/pdf', max_length=80, verbose_name='Tipo allegato')),
                ('descrizione', models.CharField(blank=True, max_length=120, verbose_name='Descrizione')),
                ('modello', models.CharField(default='libera', max_length=20, verbose_name='Riferimento')),
                ('oggetto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID oggetto')),
                ('stato', models.CharField(choices=[('attesa', 'In attesa'), ('inviata', 'Inviata'), ('fallita', 'Fallita')], db_index=True, default='attesa', max_length=20, verbose_name='Stato')),
                ('tentativi', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativi')),
                ('ultimo_errore', models.CharField(blank=True, max_length=300, verbose_name='Ultimo errore')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Accodata il')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Inviata il')),
            ],
            options={
                'verbose_name': 'Email in coda',
                'verbose_name_plural': 'Coda email',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['stato', 'created_at'], name='emailcoda_stato_idx')],
            },
        ),
    ]
