# Generated by Django 6.1.1 on 2026-10-07 14:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0004_contact_purchase_discount_pct'),
        ('jobs', '0002_remove_asset_asset_serial_idx_and_more'),
        ('sales', '0006_salesorder_order_delivered_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('color', models.CharField(choices=[('primary', 'Blu'), ('success', 'Verde'), ('danger', 'Rosso'), ('warning', 'Giallo'), ('info', 'Azzurro'), ('secondary', 'Grigio'), ('dark', 'Scuro')], default='secondary', max_length=20, verbose_name='Colore')),
                ('kind', models.CharField(choices=[('open', 'In corso'), ('won', 'Vinta'), ('lost', 'Persa')], default='open', max_length=10, verbose_name='Esito')),
            ],
            options={
                'verbose_name': 'Fase lead',
                'verbose_name_plural': 'Fasi lead',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('name', models.CharField(help_text='Es. «Rossi – piscina via Verdi».', max_length=150, verbose_name='Riferimento')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('source', models.CharField(blank=True, help_text='Es. passaparola, sito, Google, social.', max_length=80, verbose_name='Provenienza')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Valore stimato')),
                ('next_action', models.DateField(blank=True, null=True, verbose_name='Prossima azione')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='contacts.contact', verbose_name='Contatto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='jobs.job', verbose_name='Cantiere')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='sales.quote', verbose_name='Preventivo')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadstage', verbose_name='Fase')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Lead',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['stage', '-created_at'], name='lead_stage_date_idx'), models.Index(fields=['next_action'], name='lead_next_action_idx')],
            },
        ),
    ]
