# Generated by Django 6.1.1 on 2026-10-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_fasi_predefinite'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstage',
            name='on_quote_created',
            field=models.BooleanField(default=False, help_text='Quando si crea un preventivo dal lead, la trattativa passa in questa fase.', verbose_name='Fase «Preventivo mandato»'),
        ),
    ]
