# Generated by Django 6.1.1 on 2026-09-30 19:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codice')),
                ('address_note', models.CharField(blank=True, max_length=200, verbose_name='Note logistiche')),
                ('is_default', models.BooleanField(default=False, verbose_name='Magazzino predefinito')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Magazzino',
                'verbose_name_plural': 'Magazzini',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('load', 'Carico'), ('unload', 'Scarico'), ('adjust', 'Rettifica')], max_length=10, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positiva per i carichi, negativa per gli scarichi.', max_digits=12, verbose_name='Quantità')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Costo unitario')),
                ('reference', models.CharField(blank=True, help_text='Numero documento collegato', max_length=50, verbose_name='Riferimento')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.product', verbose_name='Articolo')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse', verbose_name='Magazzino')),
            ],
            options={
                'verbose_name': 'Movimento di magazzino',
                'verbose_name_plural': 'Movimenti di magazzino',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Quantità')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornata il')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.product', verbose_name='Articolo')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.warehouse', verbose_name='Magazzino')),
            ],
            options={
                'verbose_name': 'Giacenza',
                'verbose_name_plural': 'Giacenze',
                'ordering': ['product__name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_stock_per_product_warehouse')],
            },
        ),
    ]
