# Generated by Django 6.1.1 on 2026-10-01 08:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Codice')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=80, verbose_name='Cognome')),
                ('fiscal_code', models.CharField(blank=True, max_length=16, verbose_name='Codice fiscale')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('qualification', models.CharField(blank=True, max_length=100, verbose_name='Mansione')),
                ('hired_on', models.DateField(blank=True, null=True, verbose_name='Data assunzione')),
                ('terminated_on', models.DateField(blank=True, null=True, verbose_name='Data cessazione')),
                ('contract_weekly_hours', models.DecimalField(decimal_places=2, default=Decimal('40'), max_digits=5, verbose_name='Ore settimanali da contratto')),
                ('hourly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Costo orario (€)')),
                ('holiday_days_per_year', models.DecimalField(decimal_places=2, default=Decimal('26'), max_digits=5, verbose_name='Ferie annue (giorni)')),
                ('rol_hours_per_year', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Permessi annui (ore)')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Utente collegato')),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('kind', models.CharField(choices=[('holiday', 'Ferie'), ('rol', 'Permessi (ROL)'), ('sick', 'Malattia'), ('unpaid', 'Non retribuito'), ('other', 'Altro')], default='holiday', max_length=20, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Dal')),
                ('end_date', models.DateField(verbose_name='Al')),
                ('hours', models.DecimalField(blank=True, decimal_places=2, help_text='Compila solo per un permesso di poche ore nello stesso giorno; altrimenti lascia vuoto.', max_digits=5, null=True, verbose_name='Ore (solo permessi orari)')),
                ('status', models.CharField(choices=[('requested', 'Richiesta'), ('approved', 'Approvata'), ('rejected', 'Rifiutata'), ('cancelled', 'Annullata')], default='requested', max_length=20, verbose_name='Stato')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approvata il')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Approvata da')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Inserita da')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee', verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Ferie/permesso',
                'verbose_name_plural': 'Ferie e permessi',
                'ordering': ['-start_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.25'))], verbose_name='Ore')),
                ('kind', models.CharField(choices=[('ordinary', 'Ordinario'), ('overtime', 'Straordinario'), ('travel', 'Trasferta')], default='ordinary', max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrizione attività')),
                ('billable', models.BooleanField(default=False, verbose_name='Addebitabile al cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Registrato da')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='hr.employee', verbose_name='Dipendente')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='jobs.job', verbose_name='Cantiere')),
            ],
            options={
                'verbose_name': 'Registrazione ore',
                'verbose_name_plural': 'Registrazioni ore',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['active', 'last_name'], name='employee_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', '-start_date'], name='leave_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', '-start_date'], name='leave_emp_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['date', 'employee'], name='timeentry_date_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['employee', '-date'], name='timeentry_emp_date_idx'),
        ),
    ]
