# Generated by Django 6.1.1 on 2026-10-01 16:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_sale_discount_pct'),
        ('hr', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Codice')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='Ditta / attività')),
                ('fiscal_code', models.CharField(blank=True, max_length=20, verbose_name='Codice fiscale / P.IVA')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compenso orario (€)')),
                ('specialization', models.CharField(blank=True, help_text='Es. scavo, elettricista, piastrellista.', max_length=120, verbose_name='Specializzazione')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('contact', models.ForeignKey(blank=True, help_text='Facoltativo: serve se il collaboratore emette fattura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborators', to='contacts.contact', verbose_name='Contatto in anagrafica')),
                ('user', models.OneToOneField(blank=True, help_text='Utente con cui il collaboratore entra e registra le ore.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborator', to=settings.AUTH_USER_MODEL, verbose_name='Utente collegato')),
            ],
            options={
                'verbose_name': 'Collaboratore',
                'verbose_name_plural': 'Collaboratori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollaboratorTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.25'))], verbose_name='Ore')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Lavoro svolto')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='hr.collaborator', verbose_name='Collaboratore')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaborator_entries', to=settings.AUTH_USER_MODEL, verbose_name='Registrato da')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborator_time_entries', to='jobs.job', verbose_name='Cantiere / lavoro')),
            ],
            options={
                'verbose_name': 'Ore collaboratore',
                'verbose_name_plural': 'Ore collaboratori',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='collaborator',
            index=models.Index(fields=['active', 'name'], name='collab_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='collaboratortimeentry',
            index=models.Index(fields=['date', 'collaborator'], name='collabentry_date_idx'),
        ),
        migrations.AddIndex(
            model_name='collaboratortimeentry',
            index=models.Index(fields=['collaborator', '-date'], name='collabentry_collab_idx'),
        ),
    ]
