# Generated by Django 6.1.1 on 2026-10-07 14:43

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_remove_asset_asset_serial_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nome')),
                ('color', models.CharField(choices=[('primary', 'Blu'), ('success', 'Verde'), ('danger', 'Rosso'), ('warning', 'Giallo'), ('info', 'Azzurro'), ('secondary', 'Grigio'), ('dark', 'Scuro')], default='secondary', max_length=20, verbose_name='Colore')),
            ],
            options={
                'verbose_name': 'Etichetta galleria',
                'verbose_name_plural': 'Etichette galleria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/', validators=[apps.core.validators.valida_file_caricato], verbose_name='Foto')),
                ('active', models.BooleanField(default=True, verbose_name='Visibile in galleria')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to='jobs.job', verbose_name='Cantiere')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to=settings.AUTH_USER_MODEL, verbose_name='Caricata da')),
                ('tags', models.ManyToManyField(blank=True, related_name='photos', to='gallery.gallerytag', verbose_name='Etichette')),
            ],
            options={
                'verbose_name': 'Foto galleria',
                'verbose_name_plural': 'Galleria',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
