# Generated by Django 6.1.1 on 2026-09-30 19:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Categoria superiore')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Codice')),
                ('name', models.CharField(max_length=200, verbose_name='Descrizione')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione estesa')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Codice a barre')),
                ('sale_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Prezzo vendita')),
                ('purchase_price', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Usato come riferimento quando il fornitore non ha un listino.', max_digits=12, verbose_name='Prezzo acquisto')),
                ('is_stock_tracked', models.BooleanField(default=True, verbose_name='Gestito a magazzino')),
                ('min_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text="Se la giacenza scende sotto questo valore l'articolo viene evidenziato.", max_digits=12, verbose_name='Scorta minima')),
                ('notes', models.TextField(blank=True, verbose_name='Note interne')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Categoria')),
                ('main_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='contacts.contact', verbose_name='Fornitore abituale')),
                ('purchase_vat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_products', to='core.vatrate', verbose_name='IVA acquisto')),
                ('sale_vat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_products', to='core.vatrate', verbose_name='IVA vendita')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='core.tag', verbose_name='Etichette')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.unitofmeasure', verbose_name='Unità di misura')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ['name'],
            },
        ),
    ]
