# Generated by Django 6.1.1 on 2026-10-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('contacts', '0001_initial'),
        ('core', '0003_companysettings_document_color_companysettings_logo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'name'], name='product_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='product_barcode_idx'),
        ),
    ]
