# Generated by Django 6.1.1 on 2026-10-01 05:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_product_active_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_kit',
            field=models.BooleanField(default=False, help_text='Raggruppa più componenti (es. mobile + lavabo + specchio): nel preventivo puoi espanderlo.', verbose_name='Kit / composizione'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Articolo principale'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_lead_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Usato come data prevista negli ordini fornitore generati automaticamente.', verbose_name='Giorni di consegna fornitore'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_label',
            field=models.CharField(blank=True, help_text='Es. colore o finitura (Bianco, Cromo, Nero opaco…).', max_length=60, verbose_name='Variante'),
        ),
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Quantità')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_kits', to='catalog.product', verbose_name='Componente')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.product', verbose_name='Kit')),
            ],
            options={
                'verbose_name': 'Componente kit',
                'verbose_name_plural': 'Componenti kit',
                'ordering': ['component__name'],
                'constraints': [models.UniqueConstraint(fields=('kit', 'component'), name='unique_component_per_kit')],
            },
        ),
    ]
