# Generated by Django 6.1.1 on 2026-10-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_kit_product_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Codice'),
        ),
    ]
